language: julia
os:
  - linux
julia:
  - release
  - nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
  - julia -e 'Pkg.clone(pwd()); Pkg.build("GraphLayout"); Pkg.add("Compose")'
  - julia --check-bounds=yes -e 'Pkg.test("GraphLayout"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("GraphLayout")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'